name: Update Repositories

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout aktuelles Repository
        uses: actions/checkout@v3

      - name: sync.yml sichern
        run: |
          mkdir -p ../workflow_backup/.github/workflows
          cp .github/workflows/sync.yml ../workflow_backup/.github/workflows/sync.yml

      - name: Arbeitsbereich säubern (außer .git)
        run: |
          find . -mindepth 1 \
            -not -name '.git' \
            -not -path './../workflow_backup/*' \
            -exec rm -rf {} +

      - name: Clone runtipi-appstore (master) in temporäres Verzeichnis
        run: |
          git clone --branch master https://github.com/runtipi/runtipi-appstore temp_repo

      - name: Inhalte aus temp_repo in Arbeitsverzeichnis kopieren
        run: |
          shopt -s dotglob  # auch versteckte Dateien kopieren
          cp -R temp_repo/* .
          rm -rf temp_repo

      - name: Clone runtipi-backrest (main) in apps/backrest
        run: |
          mkdir -p apps
          cd apps
          git clone --branch main https://github.com/hueske-digital/runtipi-backrest backrest

      - name: .github-Ordner aus Clones entfernen
        run: rm -rf .github

      - name: sync.yml wiederherstellen
        run: |
          mkdir -p .github/workflows
          cp ../workflow_backup/.github/workflows/sync.yml .github/workflows/sync.yml

      - name: Git-Konfiguration setzen
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Änderungen committen und pushen
        run: |
          git add .
          git commit -m "Update Repositories" || echo "Nothing to commit"
          git push origin HEAD